import type {TActivityItem, TActivityStatItem} from '../types/activity.type'

const activityStatsMock: TActivityStatItem[] = [
    {
        id: 'total',
        label: 'Tổng hoạt động',
        value: '12',
        helper: 'Toàn bộ log gần đây trong hệ thống',
        tone: 'blue',
    },
    {
        id: 'customers',
        label: 'Customer actions',
        value: '4',
        helper: 'Hoạt động từ khách hàng',
        tone: 'green',
    },
    {
        id: 'shippers',
        label: 'Shipper actions',
        value: '3',
        helper: 'Hoạt động từ shipper',
        tone: 'orange',
    },
    {
        id: 'issues',
        label: 'Warnings / Errors',
        value: '2',
        helper: 'Cảnh báo hoặc lỗi cần chú ý',
        tone: 'red',
    },
]

const activitiesMock: TActivityItem[] = [
    {
        id: 'act-001',
        actorId: '2',
        actorName: 'Nguyễn Văn A',
        actorRole: 'customer',
        category: 'otp',
        status: 'success',
        title: 'Xác thực OTP thành công',
        description: 'Khách hàng đã nhập đúng OTP để mở locker A02 và nhận hàng.',
        targetId: '2',
        targetType: 'locker',
        targetLabel: 'Locker A02',
        createdAt: '2026-04-29T15:35:00Z',
        timeLabel: '5 phút trước',
    },
    {
        id: 'act-002',
        actorId: 'shipper-01',
        actorName: 'Shipper Minh',
        actorRole: 'shipper',
        category: 'shipment',
        status: 'info',
        title: 'Tạo đơn hàng mới SHP-2026-011',
        description: 'Shipper vừa tạo đơn giao mới và gán vào locker C02.',
        targetId: 'shp-011',
        targetType: 'shipment',
        targetLabel: 'SHP-2026-011',
        createdAt: '2026-04-29T15:30:00Z',
        timeLabel: '10 phút trước',
    },
    {
        id: 'act-003',
        actorId: 'admin-01',
        actorName: 'Quân Hoàng',
        actorRole: 'admin',
        category: 'settings',
        status: 'success',
        title: 'Cập nhật OTP expiry time',
        description: 'Admin thay đổi thời gian hiệu lực OTP từ 120 giây lên 180 giây.',
        targetId: 'otp-expiry',
        targetType: 'system',
        targetLabel: 'OTP Settings',
        createdAt: '2026-04-29T15:22:00Z',
        timeLabel: '18 phút trước',
    },
    {
        id: 'act-004',
        actorId: 'system-01',
        actorName: 'System Monitor',
        actorRole: 'system',
        category: 'hardware',
        status: 'warning',
        title: 'Locker B02 mất kết nối cảm biến',
        description: 'Hệ thống ghi nhận mất tín hiệu từ cảm biến cửa trong 30 giây gần nhất.',
        targetId: '4',
        targetType: 'locker',
        targetLabel: 'Locker B02',
        createdAt: '2026-04-29T15:18:00Z',
        timeLabel: '22 phút trước',
    },
    {
        id: 'act-005',
        actorId: '3',
        actorName: 'Trần Thị B',
        actorRole: 'customer',
        category: 'locker',
        status: 'info',
        title: 'Mở locker C02',
        description: 'Người dùng đã tương tác mở cửa locker sau khi xác thực hợp lệ.',
        targetId: '6',
        targetType: 'locker',
        targetLabel: 'Locker C02',
        createdAt: '2026-04-29T15:10:00Z',
        timeLabel: '30 phút trước',
    },
    {
        id: 'act-006',
        actorId: 'shipper-02',
        actorName: 'Shipper Long',
        actorRole: 'shipper',
        category: 'shipment',
        status: 'success',
        title: 'Cập nhật trạng thái shipment',
        description: 'Đơn SHP-2026-008 đã được đưa vào locker D02 thành công.',
        targetId: 'shp-008',
        targetType: 'shipment',
        targetLabel: 'SHP-2026-008',
        createdAt: '2026-04-29T15:03:00Z',
        timeLabel: '37 phút trước',
    },
    {
        id: 'act-007',
        actorId: 'admin-01',
        actorName: 'Quân Hoàng',
        actorRole: 'admin',
        category: 'user',
        status: 'info',
        title: 'Cập nhật quyền người dùng',
        description: 'Admin đã chỉnh sửa trạng thái tài khoản cho một shipper trong hệ thống.',
        targetId: 'user-shipper-02',
        targetType: 'user',
        targetLabel: 'Tài khoản shipper',
        createdAt: '2026-04-29T14:56:00Z',
        timeLabel: '44 phút trước',
    },
    {
        id: 'act-008',
        actorId: 'system-01',
        actorName: 'System Monitor',
        actorRole: 'system',
        category: 'locker',
        status: 'error',
        title: 'Mở khóa từ xa thất bại',
        description: 'Lệnh mở khóa gửi tới locker B01 không thành công do thiết bị đang maintenance.',
        targetId: '3',
        targetType: 'locker',
        targetLabel: 'Locker B01',
        createdAt: '2026-04-29T14:45:00Z',
        timeLabel: '55 phút trước',
    },
    {
        id: 'act-009',
        actorId: '2',
        actorName: 'Nguyễn Văn A',
        actorRole: 'customer',
        category: 'otp',
        status: 'warning',
        title: 'Nhập sai OTP',
        description: 'Khách hàng đã nhập sai OTP 1 lần trước khi xác thực thành công.',
        targetId: '2',
        targetType: 'locker',
        targetLabel: 'Locker A02',
        createdAt: '2026-04-29T14:39:00Z',
        timeLabel: '1 giờ trước',
    },
    {
        id: 'act-010',
        actorId: 'shipper-01',
        actorName: 'Shipper Minh',
        actorRole: 'shipper',
        category: 'shipment',
        status: 'info',
        title: 'Quét mã đơn hàng',
        description: 'Shipper đã quét mã đơn để chuẩn bị nạp vào hệ thống locker.',
        targetId: 'shp-010',
        targetType: 'shipment',
        targetLabel: 'SHP-2026-010',
        createdAt: '2026-04-29T14:28:00Z',
        timeLabel: '1 giờ 12 phút trước',
    },
    {
        id: 'act-011',
        actorId: 'admin-01',
        actorName: 'Quân Hoàng',
        actorRole: 'admin',
        category: 'settings',
        status: 'success',
        title: 'Lưu cấu hình hardware',
        description: 'Admin đã lưu lại chu kỳ heartbeat và auto refresh cho dashboard.',
        targetId: 'hardware-settings',
        targetType: 'system',
        targetLabel: 'Hardware Settings',
        createdAt: '2026-04-29T14:18:00Z',
        timeLabel: '1 giờ 22 phút trước',
    },
    {
        id: 'act-012',
        actorId: 'system-01',
        actorName: 'System Monitor',
        actorRole: 'system',
        category: 'hardware',
        status: 'success',
        title: 'Thiết bị kết nối lại',
        description: 'Locker B02 đã kết nối lại cảm biến và gửi heartbeat bình thường.',
        targetId: '4',
        targetType: 'locker',
        targetLabel: 'Locker B02',
        createdAt: '2026-04-29T14:05:00Z',
        timeLabel: '1 giờ 35 phút trước',
    },
]

export async function getActivityStats(): Promise<TActivityStatItem[]> {
    return Promise.resolve(activityStatsMock)
}

export async function getActivities(): Promise<TActivityItem[]> {
    return Promise.resolve(activitiesMock)
}

export async function getRecentActivities(limit = 5): Promise<TActivityItem[]> {
    return Promise.resolve(activitiesMock.slice(0, limit))
}

export async function getActivitiesByUserId(userId: string): Promise<TActivityItem[]> {
    return Promise.resolve(activitiesMock.filter((item) => item.actorId === userId))
}
