import type {TSettingsOverview, TSettingStatItem} from '../types/settings.type'

const settingsStatsMock: TSettingStatItem[] = [
    {
        id: 'otp-rules',
        sectionId: 'otp-settings',
        label: 'OTP Rules',
        value: '5',
        helper: 'Quy tắc OTP đang hoạt động',
        tone: 'blue',
    },
    {
        id: 'clusters',
        sectionId: 'locker-configuration',
        label: 'Clusters',
        value: '4',
        helper: 'Cụm locker đang được cấu hình',
        tone: 'green',
    },
    {
        id: 'hardware',
        sectionId: 'hardware-settings',
        label: 'Hardware',
        value: '3',
        helper: 'Thiết lập phần cứng đang dùng',
        tone: 'orange',
    },
    {
        id: 'alerts',
        sectionId: 'notification-settings',
        label: 'Alerts',
        value: '6',
        helper: 'Cảnh báo và log đang bật',
        tone: 'red',
    },
    {
        id: 'preferences',
        sectionId: 'system-preferences',
        label: 'Preferences',
        value: '3',
        helper: 'Tùy chọn hệ thống mặc định',
        tone: 'slate',
    },
]

const settingsOverviewMock: TSettingsOverview = {
    stats: settingsStatsMock,
    sections: [
        {
            id: 'otp-settings',
            title: 'OTP Settings',
            description: 'Cấu hình thời gian hiệu lực, retry và quy tắc cấp lại OTP.',
            badge: 'SYSTEM CONFIG',
            rows: [
                {
                    id: 'otp-expiry',
                    type: 'input',
                    icon: '⏱️',
                    label: 'OTP expiry time',
                    description: 'Thời gian OTP còn hiệu lực sau khi được tạo.',
                    value: '180',
                    unit: 'GIÂY',
                    inputKind: 'number',
                    min: 30,
                },
                {
                    id: 'otp-retry',
                    type: 'input',
                    icon: '🔄',
                    label: 'Max retry attempts',
                    description: 'Số lần nhập sai tối đa trước khi chặn OTP.',
                    value: '3',
                    unit: 'LẦN',
                    inputKind: 'number',
                    min: 1,
                },
                {
                    id: 'otp-regenerate',
                    type: 'toggle',
                    icon: '♻️',
                    label: 'Cho phép tạo lại OTP',
                    description: 'Admin hoặc hệ thống có thể tạo lại OTP khi cần.',
                    enabled: true,
                },
            ],
        },
        {
            id: 'locker-configuration',
            title: 'Locker Configuration',
            description: 'Thiết lập hành vi mở khóa, cluster và timeout mặc định.',
            badge: 'SYSTEM CONFIG',
            rows: [
                {
                    id: 'cluster-count',
                    type: 'input',
                    icon: '🗄️',
                    label: 'Active clusters',
                    description: 'Số cluster locker đang được kích hoạt.',
                    value: '4',
                    inputKind: 'number',
                    min: 1,
                },
                {
                    id: 'default-timeout',
                    type: 'input',
                    icon: '⌛️',
                    label: 'Default unlock timeout',
                    description: 'Thời gian chờ mặc định sau khi mở khóa.',
                    value: '8',
                    unit: 'GIÂY',
                    inputKind: 'number',
                    min: 1,
                },
                {
                    id: 'remote-unlock',
                    type: 'toggle',
                    icon: '🔓',
                    label: 'Bật mở khóa từ xa',
                    description: 'Cho phép admin thực hiện mở khóa locker từ web.',
                    enabled: true,
                },
            ],
        },
        {
            id: 'hardware-settings',
            title: 'Hardware Settings',
            description: 'Điều chỉnh heartbeat, timeout và auto refresh phần cứng.',
            badge: 'SYSTEM CONFIG',
            rows: [
                {
                    id: 'heartbeat-interval',
                    type: 'input',
                    icon: '📡',
                    label: 'Heartbeat interval',
                    description: 'Chu kỳ thiết bị gửi trạng thái về hệ thống.',
                    value: '10',
                    unit: 'GIÂY',
                    inputKind: 'number',
                    min: 1,
                },
                {
                    id: 'device-timeout',
                    type: 'input',
                    icon: '🧯',
                    label: 'Device timeout',
                    description: 'Thời gian tối đa chờ phản hồi trước khi báo offline.',
                    value: '30',
                    unit: 'GIÂY',
                    inputKind: 'number',
                    min: 5,
                },
                {
                    id: 'auto-refresh',
                    type: 'input',
                    icon: '🔁',
                    label: 'Auto refresh interval',
                    description: 'Chu kỳ làm mới trạng thái phần cứng trên admin web.',
                    value: '15',
                    unit: 'GIÂY',
                    inputKind: 'number',
                    min: 5,
                },
            ],
        },
        {
            id: 'notification-settings',
            title: 'Notification & Logs',
            description: 'Thiết lập cảnh báo lỗi, shipment bất thường và log quản trị.',
            badge: 'SYSTEM CONFIG',
            rows: [
                {
                    id: 'shipment-alerts',
                    type: 'toggle',
                    icon: '📦',
                    label: 'Bật cảnh báo shipment',
                    description: 'Thông báo khi shipment lỗi, quá hạn hoặc OTP bất thường.',
                    enabled: true,
                },
                {
                    id: 'admin-logs',
                    type: 'toggle',
                    icon: '🧾',
                    label: 'Lưu log admin action',
                    description: 'Ghi nhận thao tác mở khóa, đổi trạng thái và cấu hình.',
                    enabled: true,
                },
                {
                    id: 'device-error-alerts',
                    type: 'toggle',
                    icon: '🚨',
                    label: 'Cảnh báo lỗi thiết bị',
                    description: 'Thông báo khi relay, IR sensor hoặc reed switch gặp lỗi.',
                    enabled: true,
                },
            ],
        },
        {
            id: 'system-preferences',
            title: 'System Preferences',
            description: 'Tùy chọn hiển thị, ngôn ngữ và timezone cho admin panel.',
            badge: 'SYSTEM CONFIG',
            rows: [
                {
                    id: 'language',
                    type: 'input',
                    icon: '🌐',
                    label: 'Language',
                    description: 'Ngôn ngữ mặc định của giao diện quản trị.',
                    value: 'vi',
                    inputKind: 'select',
                    options: [
                        {label: 'Tiếng Việt', value: 'vi'},
                        {label: 'English', value: 'en'},
                    ],
                },
                {
                    id: 'timezone',
                    type: 'input',
                    icon: '🕓',
                    label: 'Timezone',
                    description: 'Múi giờ hiển thị cho shipment, user và log.',
                    value: 'UTC+7',
                    inputKind: 'select',
                    options: [
                        {label: 'UTC', value: 'UTC'},
                        {label: 'UTC+7', value: 'UTC+7'},
                        {label: 'UTC+8', value: 'UTC+8'},
                    ],
                },
                {
                    id: 'dark-surface',
                    type: 'toggle',
                    icon: '🌙',
                    label: 'Ưu tiên dark surface',
                    description: 'Giữ style nền đậm cho các khu vực control và monitoring.',
                    enabled: true,
                },
            ],
        },
    ],
}

export async function getSettingsStats(): Promise<TSettingStatItem[]> {
    return Promise.resolve(settingsStatsMock)
}

export async function getSettingsOverview(): Promise<TSettingsOverview> {
    return Promise.resolve(settingsOverviewMock)
}
